fix #2439 correctly use testNG platform for testNG task
reactor/reactor-core pull request #2444
Opened 2020-10-15 15:13 UTC by ericbottard

2020-10-15 15:22 UTC, simonbasle requested changes
I guess this also affects `3.2.x` so this should be retargeted? also is there a way to call `useJUnitPlatform` conditionally?

2020-10-15 15:29 UTC, ericbottard commented
> I guess this also affects `3.2.x` so this should be retargeted? 

My bad, I thought the testNG task was on 3.3+

> also is there a way to call `useJUnitPlatform` conditionally?

Of course, could always cite the test (junit5) tasks by name for example. But given this is the "default" throughout, I kept the "all with type Test" approach. wdyt?

2020-10-15 15:55 UTC, simonbasle commented
> > I guess this also affects `3.2.x` so this should be retargeted?
> 
> My bad, I thought the testNG task was on 3.3+
> 
> > also is there a way to call `useJUnitPlatform` conditionally?
> 
> Of course, could always cite the test (junit5) tasks by name for example. But given this is the "default" throughout, I kept the "all with type Test" approach. wdyt?

maybe "if task is testNG `useTestNG()` else `useJUnitPlatform()` then ? that would lift the need to move the `tasks.withType(Test).all` around.

2020-10-16 09:18 UTC, simonbasle approved these changes

2020-10-16 09:25 UTC, merged