fix #2467 get rid of Hamcrest matchers
reactor/reactor-core pull request #2473
Opened 2020-11-02 15:32 UTC by ericbottard

Also remove a now unused gradle version property.

2020-11-02 15:46 UTC, bsideup commented on reactor-core/src/test/java/reactor/core/publisher/scenarios/FluxTests.java
> +		assertThat(latch.getCount()).as("Not totally dispatched: ").isEqualTo(0L);
unlike with `assertThat(String, boolean)` where String is the explanation message, `as` accepts the description of the value, so it shouldn't be inverted

2020-11-02 15:52 UTC, simonbasle approved these changes

2020-11-02 16:47 UTC, bsideup approved these changes

2020-11-02 16:48 UTC, simonbasle requested changes
I think that comment applies to more or less all the occurrences of `as` that are changed in this PR. it was also the case in the Junit4->AssertJ migration, but here the scope is much more narrow and manageable. what I generally recommend is that `as` reflects purely the variable being asserted, not the assertion itself or error message.

2020-11-02 18:24 UTC, ericbottard commented
Went ahead and rephrased all `.as()` of this class. As Simon says, there could be value in a big sweep, but at least did this class.

2020-11-02 22:33 UTC, simonbasle commented
yeah to be clearer I was just advocating for covering files in this PR, since I told you not bother with that during the AssertJ PR review 👍

2020-11-03 08:38 UTC, simonbasle approved these changes

2020-11-03 08:46 UTC, merged