fix #2269 Introduce an early override of loggers in tests
reactor/reactor-core pull request #2492
Opened 2020-11-17 16:27 UTC by ericbottard

2020-11-17 16:27 UTC, ericbottard commented
I subverted `LoggerUtils` for now to prove the POC.

Please take a look @simonbasle and if we're happy with the approach I can polish.

2020-11-18 10:49 UTC, simonbasle requested changes
(I've fixed the empty `ErrorFormatterTest.java` separately, please rebase this PR on the latest master)

2020-11-18 10:49 UTC, simonbasle commented on reactor-core/src/main/java/reactor/util/Loggers.java
> +	public static void resetLoggerFactory() {
why removing the `final`s in this file ?

2020-11-18 10:49 UTC, simonbasle commented on reactor-core/src/test/java/reactor/core/publisher/OperatorsTest.java
> +
(need a TODO to complete this test, no assertion)

2020-11-18 10:49 UTC, simonbasle commented on reactor-core/src/test/java/reactor/test/LoggerUtils.java
> +		LoggerUtils.testLogger = testLogger;
I think there is still value to _provide_ a `TestLogger` as opposed to letting the method create one internally and return it. see comment about tuning logging levels.

2020-11-19 10:48 UTC, simonbasle requested changes

2020-11-19 10:48 UTC, simonbasle commented on reactor-core/src/test/java/reactor/test/LoggerUtils.java
> +			return delegate.isTraceEnabled() || (LoggerUtils.testLogger != null && LoggerUtils.testLogger.isTraceEnabled());
for the condition, capture the `testLogger` into a local variable (the `testLogger` could be nulled out between the `!= null` test and the `isTraceEnabled()` call)

2020-11-19 10:48 UTC, simonbasle commented on reactor-core/src/test/java/reactor/test/LoggerUtils.java
> +			if (LoggerUtils.testLogger != null) {
same comment as above about `testLogger` capture

2020-11-19 10:48 UTC, simonbasle commented on reactor-core/src/test/java/reactor/test/LoggerUtils.java
> +	public static void setupDivertingLoggerFactory() {
I'm on the fence about the method actually setting up the logger factory, vs returning a "factory" (as a `Function`) to pass to `Loggers.useCustomLoggers`.

2020-11-19 16:18 UTC, simonbasle commented on reactor-core/src/test/java/reactor/ReactorTestExecutionListener.java
> +	private static void resetHooksAndSchedulers() {
still needs to remove the call to old `reset()` method in `BaseOperatorTest`

2020-11-19 16:25 UTC, simonbasle requested changes

2020-11-19 16:25 UTC, simonbasle commented on reactor-test/src/main/java/reactor/test/util/LoggerUtils.java
> +	public static void enableCaptureWith(Logger testLogger) {
nitpick: I'd put the static methods above both static inner classes, and add basic documentation

2020-11-19 16:25 UTC, simonbasle commented on reactor-test/src/test/java/reactor/test/util/LoggerUtilsTest.java
> +		});
the message should be asserted

2020-11-19 16:26 UTC, simonbasle commented on reactor-core/src/test/java/reactor/test/LoggerUtils.java
> +			delegate.trace(msg);
defering this until somebody actually "complains" about the double output

2020-11-20 09:25 UTC, simonbasle approved these changes

2020-11-20 11:26 UTC, merged