fix reactor#2494 Mono.thenReturn docs clarity
reactor/reactor-core pull request #2533
Opened 2020-12-07 18:54 UTC by bbukaty

2020-12-07 18:56 UTC, bbukaty commented
I'm not sure why this didn't seem to properly link to the issue #2494 .

2020-12-07 18:56 UTC, pivotal-issuemaster commented
@bbukaty Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2533)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2533) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-12-07 18:57 UTC, pivotal-issuemaster commented
@bbukaty Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2533)!

2020-12-08 16:09 UTC, simonbasle requested changes
thanks for the PR @bbukaty ! one small nitpick on the change, otherwise looks good

2020-12-08 16:09 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Mono.java
> +	 * In other words ignore elements from this mono and transform the completion signal into a
the singular is on purpose here, as a `Mono` can only have one element.

2020-12-09 11:18 UTC, simonbasle approved these changes

2020-12-09 11:19 UTC, merged