fix #2542 metric tags are stored in map
reactor/reactor-core pull request #2543
Opened 2020-12-17 14:00 UTC by rizsotto

Metric tags are stored in a `Map<String,String>` instead of `Set<Tuple2<String,String>>` to avoid duplicated keys.

I've also changed the `scanUnsafe()` return type to the `Map.Entry<String,String>`. Happy to change that back if that's necessary, but wanted to see if within the package itself there is no blocker to do this change.

2020-12-17 14:22 UTC, simonbasle requested changes
you can't change what's part of a public API willy nilly! everything on `Scannable` must stay the same.

2020-12-18 01:17 UTC, rizsotto commented
@simonbasle updated the PR, please take a look.

2020-12-18 09:02 UTC, simonbasle requested changes
Could you add an overwriting tag test for `ParallelFluxName` as well? Otherwise looks good, thanks.

2020-12-21 23:19 UTC, rizsotto commented
@simonbasle I've added one for `ParallelFlux`.

2021-01-05 08:48 UTC, simonbasle requested changes
back from holiday break :) thanks for the updates @rizsotto. the `HashMap` usages could be turned to `LinkedHashMap` to preserve order.

2021-01-05 08:48 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/FluxName.java
> +				tags = new HashMap<>(s.tags);
ideally, I guess it would make sense to use a `LinkedHashMap` to preserve insertion order, wdyt?

2021-01-05 10:13 UTC, simonbasle approved these changes

2021-01-05 10:18 UTC, simonbasle submitted a review, later dismissed
I rebased and force-pushed to apply on top of `3.3.x` branch

2021-01-05 11:18 UTC, bsideup commented
@simonbasle just looking at the code and getting a feeling that there was _some_ reason to store it as `Set` and not `Map` - do you remember any? :D

2021-01-05 11:43 UTC, simonbasle commented
no, I can't think of any good reason for it to be a `Set`. This effectively enables storing multiple pairs with the same key (because `Tuple2` performs equality checks on both t1 and t2), which makes no sense in the context of metrics, and likely little sense in any other "tagging" context.

2021-01-05 11:50 UTC, rizsotto commented
`Set` might allow you to send the same metric keys multiple times, if the value is different. (This is supported for example by DataDog metric library, but not by micrometer metric library.)

2021-01-05 13:11 UTC, bsideup approved these changes

2021-01-05 15:15 UTC, simonbasle commented
@rizsotto I'm sorry I opened this issue without thinking about the breaking change in behavior. some people might rely on the `Flux#tag(String, String)` + `Scannable#tags()` allowing duplicate entries for the same key (although most people shouldn't, as we expect the most common pattern to be `Flux#tag`+`Flux#metrics` and the later deduplicates when publishing tags to Micrometer).

I still think that is at best a _very_ niche usecase, but I cannot risk breaking some users in a patch release. Which means we'll have to freeze that PR until 3.5.0...

Consequently, I don't think the other PR around `tags` should be moved forward before then (as the set-vs-map aspect would be put in the spotlight the minute we add that to `Flux` API, it would be bad to introduce the new operator now only to change its behavior in 3.5).

2021-01-05 23:13 UTC, rizsotto commented
Thanks @simonbasle , this is reasonable. I've closed my other PR about set the tags in one call. (My workaround in Kotlin is pretty simple, might not be efficient, but elegant.)

I'll have another question related to tags, but will shoot in a separate issue.

Ping me if you need to rebase this PR later.

2022-05-06 14:18 UTC, rizsotto commented
Hey @simonbasle ,

1.  do you want that `Scannable.tags()` fix on top of this PR, or it should be a separate one?
2. Any preferred or recommended way to solve the problem?

2022-05-06 14:31 UTC, simonbasle commented
I'm actually starting to think we should embrace the "store duplicates" (going from `Set` to `List` rather than `Map`, so that `Stream<TAG>` is always presenting all duplicates in declaration order), then focus on `Scannable#tags` method to remove said duplicates, perhaps by adding a `Map<String, String> tagsDeduplicated()` method to `Scannable` ?

2022-05-06 15:32 UTC, rizsotto commented
Yes, that makes sense... Store in a `List` (instead of `Set`) will save you the hash time. But you can skip the dedup completely, because the underlying metric library will do it for you. :) I am happy to do what you were suggesting. Should it be this PR, or a new one?

To be honest, on the project I am working, we had to avoid the `tag`, `name`, `metric` and `log` methods completely and re-do it on top of the `Mono` interface with `doOnCancel`, `doOnError` and `doOnSuccess`. The reasons were:

- Too many fake cancellation metrics shows up. (Could not create SLO metrics from these.)
- Can't use the same tags for both metrics and logging. (Although some tags are not safe to be as metric: cardinality issues.)

What I did was to re-purpose the context, to store the tags. Created a `Tag` type (with a `Boolean isMetricSafe()` method), which is recognized when metrics/logging sending is done. And avoid to have separate `name` and `metric` methods, the new `measure` method takes the metric name as parameter. And a new `log` method also scanning the context for tags and insert it into `StructuredArguments`, so it really looks like `MDC` like logging.

I know these changes would be too big to applied here. I just wanted to give a little feedback. And maybe inspire some future version.

2022-05-06 15:58 UTC, simonbasle commented
> I know these changes would be too big to applied here. I just wanted to give a little feedback. And maybe inspire some future version.

Since `3.5.0-M2` there is a `Flux.tap` operator that allows to do custom logging or metrics or "doOn-like" operators, but with per-Subscriber state. Maybe that can be applied to simplify you custom logic? See #3013.

We are extracting a dedicated module for micrometer metrics in replacement for the `metrics()` operator, and that module relies on `tap`: it provides a listener to pass to `tap`. See #3015.

> Should it be this PR, or a new one?

I think we probably want to close this one and open a new one, although it would probably change a lot of the same files.

Let me gather my thoughts in the issue, and I'll edit to point to my comment here.

2022-05-06 16:17 UTC, simonbasle commented
@rizsotto I've also tried to describe the new expected behavior in the form of javadoc [here](https://github.com/reactor/reactor-core/issues/2542#issuecomment-1119780715)

2022-05-09 08:29 UTC, closed without merging

2022-05-09 09:34 UTC, simonbasle commented
@rizsotto I have a bit of time today to work on this, unless you've made some progress already?

2022-05-09 09:38 UTC, rizsotto commented
@simonbasle I have not started, please go ahead.