Clarify onErrorContinue() use
reactor/reactor-core pull request #2662
Opened 2021-03-24 20:22 UTC by berry120

From discussions around `onErrorContinue()`, it was agreed that it'd be helpful if the documentation more clearly referenced the fact that it's a specialist operator, and highlighted some of the potential problems with it (as well as the `onErrorResume()` on the inner flatmap publisher pattern which could be used instead.)

I've written some documentation which I hope explains this without being *too* wordy, though very open to suggestions!

2021-03-25 14:11 UTC, simonbasle requested changes
thanks @berry120 the wording sounds good. The snippets can be slightly improved (as commented) and might benefit from demonstrating a `doOnError` (to demonstrate how to log the skipped exception or do something similar to the `onErrorContinue` consumer).
Then the same change needs to be applied to `Mono` as well.

2021-03-25 14:11 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Flux.java
> +	 * <pre>.flatMap(id -> repository.retrieveById(id).onErrorResume(e -> Mono.empty()))</pre>
snippet should reflect the Class parameter from this overload

2021-03-25 14:11 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Flux.java
> +	 * <pre>.flatMap(id -> repository.retrieveById(id).onErrorResume(e -> Mono.empty()))</pre>
snippet should reflect the errorPredicate parameter from this overload

2021-03-25 14:11 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Flux.java
> +	 * it. Specifically, you can use `onErrorResume(e -> Mono.empty())` on each inner flatMap
maybe use `{@code shortInlineSnippet}` format rather than markdown-style backticks?

2021-03-25 14:11 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Flux.java
> +	 * it. Specifically, you can use `onErrorResume(e -> Mono.empty())` on each inner flatMap
maybe use `{@code shortInlineSnippet}` format rather than markdown-style backticks?

2021-03-25 14:11 UTC, simonbasle commented on reactor-core/src/main/java/reactor/core/publisher/Flux.java
> +	 * it. Specifically, you can use `onErrorResume(e -> Mono.empty())` on each inner flatMap
maybe use `{@code shortInlineSnippet}` format rather than markdown-style backticks?

2021-03-25 16:12 UTC, UgiR commented
Happy to see this in the doc officially!

2021-03-25 18:41 UTC, berry120 commented
@simonbasle Yup, agreed with all those points - I'll make those changes and update the PR 👍

2021-03-26 17:32 UTC, berry120 commented
@simonbasle I've made those changes to `Mono`  too and addressed the other review points (including the use of `doOnError()` for logging.)

2021-03-29 13:56 UTC, simonbasle approved these changes

2021-03-29 13:57 UTC, simonbasle commented
Thanks @berry120 that looks good 👍

2021-03-29 14:02 UTC, simonbasle commented
@berry120 @UgiR @piotrplazienski do you think we can close #2184 with this one?
(we can still separately introduce a `scope` operator and move that tricky API under an `unsafe()` group later on)

2021-03-29 14:03 UTC, berry120 commented
@simonbasle Yup, I'd agree since we all agreed improving the documentation would be a good initial step at least as the outcome of that task, and it was more of a discussion anyway.

2021-03-29 14:33 UTC, piotrplazienski commented
Yes, this is exactly what would prevent me from using it :).
Maybe you can also add case to https://projectreactor.io/docs/core/release/reference/#faq?

2021-03-29 15:30 UTC, merged