Use gradle-build-action for invoking Gradle on CI
reactor/reactor-core pull request #2828
Opened 2021-11-01 19:01 UTC by bigdaz

The `gradle/gradle-build-action` replaces `eskatos/gradle-command-action`, and `v2` brings a number of improvements around caching and usability.

2021-11-02 11:14 UTC, simonbasle requested changes
thanks for the suggestion @bigdaz !
this looks good to me. 

would you be willing however to re-target this PR on the `3.3.x` branch? (github workflows should be the same there).

also have a single doubt on the last set of arguments (see inline comment)

2021-11-02 11:14 UTC, simonbasle commented on .github/workflows/publish.yml
> +          -Partifactory_publish_repoKey=libs-release-local publishMavenJavaPublicationToSonatypeRepository
shouldn't the last task be on its own line ?

2021-11-02 16:22 UTC, bigdaz commented
PR rebased on `3.3.x` branch and `publish.yml` fixed as requested.

2021-11-04 08:42 UTC, simonbasle approved these changes

2021-11-04 08:49 UTC, simonbasle commented
checks are still shown as "waiting" despite at least one restarted and passing. I'll just close and reopen this PR to force a trigger of checks again.

2021-11-04 09:04 UTC, merged

2021-11-04 09:14 UTC, simonbasle commented
wait, these are not only replacing the `eskatos` usage, but also the `run` usage. we decided that for publishing artifacts we'd avoid 3rd party gh actions as much as possible. I'll revert that part on 3.3.x before forward merging the CI.yml change only.