Remove deprecated ElasticScheduler
reactor/reactor-core pull request #2955
Opened 2022-03-09 19:06 UTC by simonbasle

Fixes #2207.

2022-03-09 19:35 UTC, violetagg approved these changes

2022-03-10 06:51 UTC, violetagg requested changes
There are some failing tests on the CI

2022-03-10 10:03 UTC, simonbasle commented
@violetagg tests should be fixed now

2022-03-10 10:49 UTC, violetagg approved these changes

2022-03-10 13:34 UTC, merged