Update ReactorDebugAgent docs to include buildpack examples
reactor/reactor-core pull request #2987
Opened 2022-03-29 17:39 UTC by kryspetrie

2022-03-30 10:22 UTC, simonbasle commented
This is a bit too specific to buildpacks and Spring Boot. I don't think we'd want to describe stack-specific configuration options in the documentation of Reactor. Any middle ground you can find? Or maybe this rather belongs in another of these projects (packeto, Spring Boot Maven/Gradle plugins, ...), but in a more generic wording.

2022-03-30 10:23 UTC, simonbasle requested changes
This is a bit too specific to buildpacks and Spring Boot. I don't think we'd want to describe stack-specific configuration options in the documentation of Reactor. Any middle ground you can find? Or maybe this rather belongs in another of these projects (packeto, Spring Boot Maven/Gradle plugins, ...), but in a more generic wording.

2022-03-30 10:57 UTC, simonbasle commented
An additional issue with your documented remediation is that it forces the buildpack to use a JDK instead of a JRE, which seems to be considered a security concern in production...

Since the documentation of the agent mentions how to attach it as a jar via `java -javaagent`, I would recommend that approach instead.

See the `java-buildpack` [configuration and extension](https://github.com/cloudfoundry/java-buildpack/blob/main/README.md#configuration-and-extension) section which has an example around `javaagent`.

2022-03-30 18:13 UTC, kryspetrie commented
@simonbasle Thank you for the feedback! Still trying to find the best place to put this information; it's "integration" level information, so that's what makes it tricky, especially since Springdocs do not mention the ReactorDebugAgent at all.

Will look into less heavy-hammered approaches.

2022-04-11 20:19 UTC, closed without merging

2022-04-11 20:19 UTC, kryspetrie commented
Will make new PR once we do this a better way, perhaps in the spring docs instead.