Fix: splitting a long doc sentence to 2
reactor/reactor-core pull request #3079
Opened 2022-06-17 08:33 UTC by lynch19

2022-06-17 08:33 UTC, pivotal-cla commented
@lynch19 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3079)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=3079) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-06-17 08:35 UTC, pivotal-cla commented
@lynch19 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3079)!

2022-06-17 08:41 UTC, simonbasle requested changes
I understand the spirit and that sentence is indeed a bit long, but the split is not great. what comes after the `:` is a single sentence. the idea was to convey that a different index is used for computing retry delays and deciding whether to retry or not. that index is reset to 0 in case of onNext.

2022-06-17 16:19 UTC, lynch19 commented
For new users, it's really hard to understand what's going on in this paragraph. Notice that this is the first time in the docs that the word "index" is referenced (raises the question: "What index?").
* Notice `RetrySignal`'s use isn't clear for new users. There is no code example for its implementation usages nor explanations for its implementations at all.
* The word "index" doesn't appear in this interface nor the interface's Javadoc. `ImmutableRetrySignal#totalRetriesInARow()` and `RetryWhenMainSubscriber#totalRetriesInARow()` do return a `this.failureSubsequentIndex`, but this seems pretty irrelevant if there's no further explanation for the both of them.

As long as my suggestion will be correct (I'm pretty new to the subject of retrying. Trying to fix the parts I've didn't understand from the docs), I suggest rephrasing the unclear:
> Transient error handling in the `Retry` specs makes use of `RetrySignal#totalRetriesInARow()`: to check whether to retry or not and to compute the retry delays, the index used is an alternative one that is reset to 0 each time an `onNext` is emitted.

to: 
"Transient error handling in the `Retry` specs (like `RetryWhenMainSubscriber`, `ImmutableRetrySignal`) makes use of `RetrySignal#totalRetriesInARow()`: to check whether to retry or not and to compute the retry delays. They use an index that is reset to 0 each time an `onNext` is emitted (this is the number of errors -1 since the latest `onNext`)."

In general, I think that there's should be a new scope for `==== Transient Errors`, and that the `RetrySignal` section should contain another concrete code example.

And also I have a little question that I think needs to be answered inside the docs - In the initial retrying example (the one with the interval ticks) there was shown how to retry the whole flux. What if I'd like to retry only the specific error-causing item? e.g. I think that many (I'm included) would like to know how to produce the output of:
```
259,tick 0
249,tick 1
251,tick 2
java.lang.RuntimeException: boom
java.lang.RuntimeException: boom
```
instead of:

```
259,tick 0
249,tick 1
251,tick 2
506,tick 0 
248,tick 1
253,tick 2
java.lang.RuntimeException: boom
```
This can be shown in a more appropriate example (that can demonstrate a temporary network-caused IO exception).

2022-06-29 08:14 UTC, simonbasle commented
ok, it sounds like the concept of transient error needs more explaining and a more detailed section (eg. TIP) in the reference guide. I'll open a separate PR. This split is too naive and prone to introducing confusion. Keep in mind this mode is opt-in, and not the norm for a `RetrySpec`.

2022-06-29 08:14 UTC, closed without merging