Rework guide on Retry with Transient Errors
reactor/reactor-core pull request #3093
Opened 2022-06-29 09:31 UTC by simonbasle

This commit reworks the reference guide section on Retry with Transient
Errors, improving the explanation and adding more details in a separate
section.

The code snippet has also been changed to reflect a more practical use
case, with the original artificial `Flux<Integer>` split out in a
secondary snippet.

Supersedes #3079.

2022-06-29 09:32 UTC, simonbasle commented
@lynch19 FYI this PR is my rework of the explanations around transient error `retry`.

2022-06-29 10:28 UTC, violetagg requested changes
please fix the copyright end year

2022-06-29 10:51 UTC, violetagg requested changes

2022-06-29 10:51 UTC, violetagg commented on docs/asciidoc/coreFeatures.adoc
> +<6> At the end, a valid response is achieved and the `transientFlux` successfully completes after `6` attempts have been registered in `errorCount`.
Is `<5>` should be `<3>`, `<6>` should be `<4>`

2022-06-29 10:51 UTC, violetagg commented on reactor-core/src/test/java/reactor/guide/GuideTests.java
> +transientFlux.retryWhen(Retry.max(2).transientErrors(true))  // <3>
Here is there something wrong with the formatting?

2022-06-29 12:03 UTC, violetagg approved these changes

2022-06-30 09:52 UTC, simonbasle commented
@lynch19 I'll defer merging until tomorrow to give you a chance to review the wording and confirm this makes the documentation more understandable

2022-07-06 12:33 UTC, merged