Update retryWhen docs on deprecated currentContext
reactor/reactor-core pull request #3283
Opened 2022-11-16 01:42 UTC by cbrunsdon

This should now be pointing to contextView as currentContext is deprecated

@pivotal-cla This is an Obvious Fix

2022-11-16 14:59 UTC, simonbasle requested changes
nice catch ! I think there are other places where a similar change could be implemented, notably the `FluxSink` and `MonoSink` javadocs deprecation notice for `currentContext()`.

also, the notices and deprecations have been put as early as the `3.4.x` branch. would you mind retargetting your PR to that branch instead? 🙇

2022-11-16 17:49 UTC, cbrunsdon commented
Retargetted to 4.3 and picked up the other two instances, thanks.

Couldn't find anything else wrongly referencing `getContextView`, all remaining instances (on the 4.3.x branch anyway) are for the `Signal` method.

2022-11-23 08:34 UTC, OlegDokuka approved these changes

2023-06-21 10:19 UTC, merged

2023-06-21 10:21 UTC, OlegDokuka commented
@cbrunsdon great work! Thanks for your improvements!