Fix auto-cancelled Sinks.many() accepting emissions
reactor/reactor-core pull request #3725
Opened 2024-02-12 13:24 UTC by kaqqao

Fixes #3715

2024-02-12 13:24 UTC, pivotal-cla commented
@kaqqao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3725)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=3725) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-02-12 13:24 UTC, pivotal-cla commented
@kaqqao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3725)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=3725) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-02-12 13:27 UTC, pivotal-cla commented
@kaqqao Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3725)!

2024-02-23 11:07 UTC, chemicL commented on reactor-core/src/test/java/reactor/core/publisher/SinksTest.java
Please also run `spotlessApply` task for this file.

2024-02-23 13:54 UTC, chemicL commented
Thanks so much for the effort so far! 🎉 

I think the proposed implementation which checks for cancellation upon emission attempts looks simple and elegant. Unfortunately, I'm not sure it's correct. It would definitely improve the situation. However, I am worried about potential races. As I understand this improvement would prevent unnoticed leaks of values that end up in the queue despite having the sink already unusable. In concurrent scenarios, with the proposed implementation I think there is a risk that the cancellation is about to be triggered while an item is offered.

`T1`: cancelling thread
`T2`: emitting thread

Timeline:

```
T1: ---------------------------- L607:terminate() -- L610:q.clear() ------------------->
T2: L253:isCancelled()-> false -------------------------------------- L279:q.offer(t) ->
```

As far as I understand, the access to this `Sink` implementation is serialized however only from the producer perspective, so this race is possible. Probably you can confirm that using a JCStress test (it would be neat to add one for this case).

Do you agree about the risk? Would you be willing to verify and improve the implementation? Thanks in advance for your effort!

2024-02-23 13:55 UTC, chemicL requested changes
Thanks so much for the effort so far! 🎉 

I think the proposed implementation which checks for cancellation upon emission attempts looks simple and elegant. Unfortunately, I'm not sure it's correct. It would definitely improve the situation. However, I am worried about potential races. As I understand this improvement would prevent unnoticed leaks of values that end up in the queue despite having the sink already unusable. In concurrent scenarios, with the proposed implementation I think there is a risk that the cancellation is about to be triggered while an item is offered.

`T1`: cancelling thread
`T2`: emitting thread

Timeline:

```
T1: ---------------------------- L607:terminate() -- L610:q.clear() ------------------->
T2: L253:isCancelled()-> false -------------------------------------- L279:q.offer(t) ->
```

As far as I understand, the access to this `Sink` implementation is serialized however only from the producer perspective, so this race is possible. Probably you can confirm that using a JCStress test (it would be neat to add one for this case).

Do you agree about the risk? Would you be willing to verify and improve the implementation? Thanks in advance for your effort!

2024-03-20 11:54 UTC, chemicL commented
@kaqqao are you still interested in this?

2024-04-11 10:21 UTC, chemicL commented
Closing due to lack of activity. Please reopen if you'd like to follow-up.

2024-04-11 10:21 UTC, closed without merging

2024-04-17 05:25 UTC, bajibalu commented
Hi @chemicL I am interested to work on this issue if this issue is still open for pickup. Ideally, the queue should not accept any more items once the sink is canceled. Wondering would adding a function to the `SpscArrayQueue` / `SpscArrayQueueCold` to freeze the queue will help?