Fixes issue #3697 disposing TimedRunnable if disposed before scheduling
reactor/reactor-core pull request #3780
Opened 2024-04-04 13:10 UTC by kkondratov

Addresses the issue with TimedScheduler pending task leaks as described in https://github.com/reactor/reactor-core/issues/3697

The chosen approach splits existing TimedRunnable into two implementations and moves code from the TimedScheduler into the TimedRunnable to reduce duplication.
Two implementations `WorkerBacked/SchedulerBackedTimedRunnable` are present to differentiate between scheduler or a worker that schedules a task (since there is no shared interface between those). 
Differentiating from the initial proposed in #3697 by @nathankooij there is no extra objects being created and the scheduling is delegated to TimedRunnable.

Fixes #3697

2024-04-10 09:16 UTC, chemicL requested changes
Great work! Thanks :) Please rebase to target the 3.5.x branch and we can merge.

2024-04-10 13:52 UTC, kkondratov commented
@chemicL I think I've rebased correctly and targeting 3.5.x branch now as requested.

2024-04-11 08:13 UTC, chemicL approved these changes

2024-04-11 08:21 UTC, merged

2024-04-11 08:25 UTC, chemicL commented
Thank you for the contribution @kkondratov! Great job and please consider contributing in the future :) 🚀

2024-04-11 09:07 UTC, chemicL commented
Please note the new tests failed when the target branch CI job was run: https://github.com/reactor/reactor-core/actions/runs/8643683792/job/23697225902

I corrected the flakiness of the tests in d11ea71b5c28271a2d1b5cbb0b11ee8dc84c9b4b – please have a look. The tests assumed that active and pending are both equal to 1 when one task is able to run and the other should be waiting. However a situation can happen in which the Runnable is not yet being executed and has not yet decremented the pending counter.

2024-04-11 09:10 UTC, chemicL commented
There are other issues of such nature in that test class, e.g. ignoring the result of `CountDownLatch#await` - 10 seconds can pass and the call returns false, while the test should immediately fail. Feel free to open a PR if you're inclined to improve it :)