Improve auto context propagation in lifting and ConnectableFlux intersection
reactor/reactor-core pull request #3787
Opened 2024-04-17 13:48 UTC by chemicL

Combining ConnectableFlux or Fuseable operators and wrapping via Hooks could lead to ClassCastException or lack of ThreadLocal restoration. ConnectableFlux and Fuseable handling has been improved. Also, lifting now avoids unnecessary multiple-wrapping.

Fixes #3762

2024-04-24 09:52 UTC, violetagg requested changes

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/FluxContextWriteRestoringThreadLocalsFuseable.java
> + * Copyright (c) 2016-2024 VMware Inc. or its affiliates, All Rights Reserved.
```suggestion
 * Copyright (c) 2024 VMware Inc. or its affiliates, All Rights Reserved.
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/ConnectableLift.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/ConnectableLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/GroupedLift.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/GroupedLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/MonoLift.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/MonoLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/ParallelLift.java
> +					Objects.requireNonNull(liftFunction.lifter.apply(source, s[i]),
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
					Objects.requireNonNull(liftFunction.lifter.apply(source, s[i]),
```

2024-04-24 09:52 UTC, violetagg commented on reactor-core/src/main/java/reactor/core/publisher/ParallelLiftFuseable.java
> +					Objects.requireNonNull(liftFunction.lifter.apply(source, actual), "Lifted subscriber MUST NOT be null");
```suggestion
		// No need to wrap actual for CP, the Operators$LiftFunction handles it.
					Objects.requireNonNull(liftFunction.lifter.apply(source, actual), "Lifted subscriber MUST NOT be null");
```

2024-04-30 10:02 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/ConnectableLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
✅

2024-04-30 10:03 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/GroupedLift.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
✅

2024-04-30 10:03 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/GroupedLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
✅

2024-04-30 10:03 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/MonoLift.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
✅

2024-04-30 10:03 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/MonoLiftFuseable.java
> +		CoreSubscriber<? super I> input = liftFunction.lifter.apply(source, actual);
✅

2024-04-30 10:04 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/ParallelLift.java
> +					Objects.requireNonNull(liftFunction.lifter.apply(source, s[i]),
✅

2024-04-30 10:04 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/publisher/ParallelLiftFuseable.java
> +					Objects.requireNonNull(liftFunction.lifter.apply(source, actual), "Lifted subscriber MUST NOT be null");
✅

2024-04-30 10:05 UTC, violetagg approved these changes

2024-05-06 11:34 UTC, merged

2024-05-06 11:34 UTC, chemicL commented
@violetagg thank you for the review!