Allow registering a custom `Predicate` for determining non-blocking threads
reactor/reactor-core pull request #3847
Opened 2024-07-15 12:51 UTC by trustin

Related issue: #3833
Motivation:

It is currently not possible to create a non-blocking threads without implementing the `reactor.core.scheduler.NonBlocking` interface. Some third-party libraries and frameworks don't directly depend on `reactor-core`, yet they want to mark the threads they manage as non-blocking.

Modifications:

- Added a new method `Schedulers.registerNonBlockingThreadPredicate()` so that a user can register their own `Predicate` that determines whether a given thread is non-blocking or not
- Fixed an incorrectly implemented test that doesn't really test anything:
  - `SchedulersTest.isInNonBlockingThreadTrue()`

Result:

- Closes #3833
- A user can now mark their own `Thread` classes as non-blocking without depending on `reactor-core` or implementing the `NonBlocking` marker interface.

2024-07-15 12:51 UTC, pivotal-cla commented
@trustin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3847)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=3847) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-07-15 12:51 UTC, pivotal-cla commented
@trustin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3847)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=3847) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-07-15 12:53 UTC, pivotal-cla commented
@trustin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=3847)!

2024-07-16 16:02 UTC, chemicL requested changes
Thank you for following up with the PR. I have just one request, but overall it looks neat and will be happy to merge once the reset functionality is added.

2024-07-16 16:02 UTC, chemicL commented on reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
> +			}
I like this pattern, thanks! In other places we set the check using some atomic type, utilize a latch and then combine the await with an assertion. This allows to use the assertions API directly, awesome.

2024-07-17 09:41 UTC, chemicL commented
Just noticed the branch is targeting main. As this is an additive change, I think we could ship this in 3.6.9. Or are you ok to delay this until 3.7.0? Adding functionality in patch brings a bit of an effort to the usages where the actual runtime library might have the API or might not so you need a way to check if you can register the `Predicate`.

2024-07-22 11:30 UTC, trustin commented on reactor-core/src/test/java/reactor/core/scheduler/SchedulersTest.java
> +			Schedulers.nonBlockingThreadPredicate = Schedulers.DEFAULT_NON_BLOCKING_THREAD_PREDICATE;
Added `Schedulers.resetNonBlockingThreadPredicate()` and updated the test.

2024-07-22 11:31 UTC, trustin commented
That's a good idea, @chemicL. Let me send another PR that targets 3.6 soon. :bow:

2024-07-22 11:38 UTC, trustin commented
@chemicL, I sent a new pull request for 3.6: #3854

2024-07-22 14:51 UTC, chemicL commented
Thanks, closing this one then.

2024-07-22 14:51 UTC, closed without merging