Defer `Scannable#name()` fallback logic
reactor/reactor-core pull request #3900
Opened 2024-10-03 06:59 UTC by Stephan202

Depending on the implementation, `Scannable#stepName()` may be expensive 
to invoke. As such this should only happen when necessary.

2024-10-03 07:05 UTC, Stephan202 reviewed
Hat tip to @werli for spotting this issue!

2024-10-03 11:00 UTC, Stephan202 commented on reactor-core/src/main/java/reactor/core/Scannable.java
> +				.orElseGet(this::stepName);
> I'll file a separate PR with benchmark for that, and link it here afterwards.

Done: #3901.

2024-10-03 12:04 UTC, werli approved these changes
Assuming `Scannable#stepName` does not create important side effects, this should be a net-positive. 💪 

Thanks for filing the PR @Stephan202!

2024-10-04 08:25 UTC, chemicL requested changes
@Stephan202 thanks for the PR. It looks promising. As suggested in the comment, can you please merge this work with the other PR? Thanks.

2024-10-04 08:25 UTC, chemicL commented on reactor-core/src/main/java/reactor/core/Scannable.java
> +				.orElseGet(this::stepName);
Sounds reasonable to move the changes from this PR to #3901 as they are related and the whole context is there.

2024-10-04 17:04 UTC, Stephan202 commented
@chemicL done: #3901 has been updated. I'll close this PR.

2024-10-04 17:04 UTC, closed without merging