verify inflight mono's cancelled for mono firstWithValue
reactor/reactor-core pull request #3915
Opened 2024-11-04 01:04 UTC by subbarao

Adding missing tests for MonoFirstWithValue.

MonoFirstWithValue tests which verifies cancellation of in flight publishers when first value is emitted is missing. 
If you comment https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/FluxFirstWithValue.java#L283 current tests will pass.
In this test case we start three monos with 3 different sleep. Once Mono with lowest delay completes we verify remaining
monos are cancelled.

2024-11-05 19:13 UTC, violetagg commented
@subbarao We definitely will make a review so bear with us.

2024-11-06 13:06 UTC, chemicL requested changes
@subbarao thanks for the PR. Please rewrite your test in a way that avoids `Thread.sleep()` but relies on more reliable and timely synchronization mechanisms, e.g. `CountDownLatch`. Using `Thread.sleep` in tests and relying on actual time passing contributes negatively to the overall CI duration and can also be prone to flakiness due to different scheduling, delays, etc.

2024-11-07 04:50 UTC, subbarao commented
> @subbarao thanks for the PR. Please rewrite your test in a way that avoids `Thread.sleep()` but relies on more reliable and timely synchronization mechanisms, e.g. `CountDownLatch`. Using `Thread.sleep` in tests and relying on actual time passing contributes negatively to the overall CI duration and can also be prone to flakiness due to different scheduling, delays, etc.

updated pr

2024-11-07 08:01 UTC, chemicL approved these changes
Thank you for applying the review comment and your contribution! 🚢

2024-11-07 09:18 UTC, merged

2024-11-12 09:11 UTC, chemicL commented
This test seems to be flaky though. I just had it fail after a PR merge in https://github.com/reactor/reactor-core/actions/runs/11793828102

```
Test class reactor.core.publisher.MonoFirstWithValueTest


MonoFirstWithValueTest > cancelInflightMono() FAILED
    java.lang.AssertionError: 
    Expecting AtomicLong(1) to have value:
      2L
    but did not.
        at reactor.core.publisher.MonoFirstWithValueTest.cancelInflightMono(MonoFirstWithValueTest.java:205)
```

I will revert. Please try evaluating it by running the test e.g. 1k times (Intellij IDEA allows you to do that using non-gradle test run) and make sure there's some synchronization.

2024-12-02 12:53 UTC, chemicL commented
@subbarao are you interested in revisiting this topic?

2024-12-02 21:34 UTC, subbarao commented
> @subbarao are you interested in revisiting this topic?

will submit pr for this by end of the week.